Redesign explorer to just do good path handling (Closes #30)
ksunden/h5cli pull request #42
Opened 2017-10-11 04:41 UTC by lphk92

2017-10-13 04:21 UTC, ksunden requested changes
Is there any functionality that is known to be lost in this transition (I don't see any, just want to make sure)

2017-10-13 04:21 UTC, ksunden commented on src/cli.py
> +import explorer
This needs to be a relative import for execution outside of the src directory (e.g. from the distutils generated entrypoint)

2017-10-13 04:21 UTC, ksunden commented on src/cli.py
> +        self.explorer = new_explorer.NewH5Explorer.from_file(args[0], mode=opts.mode)
I am getting a NameError new_explorer is not defined here

2017-10-13 04:21 UTC, ksunden commented on src/explorer.py
> +        return NewH5Explorer(h5_file)
NewH5Explorer not defined

2017-10-13 04:21 UTC, ksunden commented on src/explorer.py
> +        return NewH5Explorer(result)
drop the New

2017-10-13 04:32 UTC, ksunden commented
@lphk92 I fixed all the errors I found, but I do want to give you the opportunity to check my changes/ensure I didn't miss anything that my changes remind you of.

Once I hear from you, I am ready to merge this

2017-10-13 04:42 UTC, ksunden commented on src/cli.py
> +import explorer
I am noticing that it fails running directly from src with the relative import, but it fails from `h5cli` without it, and that is, in my opinion, how it should be accessed in the future

2017-10-14 08:55 UTC, lphk92 commented
@ksunden How are you running this locally? When I try to run it with the relative import in there I get the following error:

`Traceback (most recent call last):
  File "./src/cli.py", line 3, in <module>
    from . import explorer
SystemError: Parent module '' not loaded, cannot perform relative import`

2017-10-14 10:30 UTC, lphk92 commented
This answer on StackOverflow provides a lot of useful context that to me makes a compelling argument as to why it might make more sense to structure the project such that we have an absolute import there:

https://stackoverflow.com/questions/16981921/relative-imports-in-python-3/28154841#28154841

2017-10-14 10:50 UTC, lphk92 commented
Just put up a patch that creates a separate script for running locally so relative import works

2017-10-15 03:20 UTC, ksunden approved these changes

2017-10-15 03:21 UTC, merged