Shape command, with flag for size (closes #22, closes #21), see also #29
ksunden/h5cli pull request #51
Opened 2017-10-15 04:33 UTC by ksunden

2017-10-15 04:49 UTC, ksunden commented
One comment, the current implementation has an exception if the referenced item is not a dataset.

We could make it print the shape for each dataset in a group (possibly with a `-r` flag as an option)

2017-10-15 13:54 UTC, lphk92 commented on src/h5cli/cli.py
> +        if opts.maxshape:
Make this an `elif`

2017-10-15 13:55 UTC, lphk92 commented on src/h5cli/cli.py
> +        print(self.explorer[args[0]].shape)
Put this in an else, and just return False once at the bottom of the function

2017-10-15 13:57 UTC, lphk92 commented on src/h5cli/cli.py
> +        make_option('-m', '--maxshape',action='store_true', help='print maximum shape, rather than current shape')
From the logic in the function it seems like these two options are mutually exclusive. Is there a way to specify that these options can't go together?

2017-10-15 13:58 UTC, lphk92 requested changes
Left some comments on structure of command. In summary:

- Make it an actually set if..elif..else block in the function and just return once
- We need to have some way of telling the user that the two options are mutually exclusive.

2017-10-15 17:12 UTC, ksunden commented
Not sure we can make them strictly mutually exclusive, but we can make them write to the same destination variable, in which opt parse will result in the value from the last option

2017-10-15 18:48 UTC, ksunden commented
```
[ultrafast.hdf5: /] > shape 1D/T
(81,)
[ultrafast.hdf5: /] > shape -n 1D/T
81
[ultrafast.hdf5: /] > shape -nm 1D/T
(81,)
[ultrafast.hdf5: /] > shape -nmn 1D/T
81
```

2017-10-18 01:46 UTC, ksunden commented
ping @lphk92

2017-10-22 11:03 UTC, lphk92 approved these changes

2017-10-22 11:05 UTC, merged